version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

#     - run: npm install

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless


      - run:
          name: Install npm dependencies
          command: |
            npm install

#      - run:
#          name: Deploy to AWS
#          command: |
#            serverless deploy -v


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

